# test_kmgpt.sub
# Configured for Docker universe to run a Docker container job in HTCondor

# Docker universe specification
universe = docker

# Specify the Docker image to use
docker_image = docker://1234162344/relevant_hyp_filter:latest

# The executable is a script or command that resides in the current directory, which will be transferred to the Docker container
executable = test_kmgpt.sh

# Specify file transfer behavior and the files to be transferred
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ., ../src/*

# Output, error, and log file settings
output = test_kmgpt_$(Cluster)_$(Process).out
error = test_kmgpt_$(Cluster)_$(Process).err
log = test_kmgpt_$(Cluster).log

# Request GPU resources
request_gpus = 1
#+WantGPULab = true
+GPUJobLength = "short"  

# It's recommended to request at least 1 CPU and suitable memory and disk for your task
request_cpus = 1
request_memory = 32GB  
request_disk = 10GB  

stream_error = true 
stream_output = true

# Custom requirements for a specific type of GPU, if needed
# require_gpus = (Capability >= 8.0) && (GlobalMemoryMb >= 40000)

# Job queueing
queue 1

