# hello-world.sub
# My HTCondor submit file
	
# Specify your executable (single binary or a script that runs several
#  commands) and arguments to be passed to jobs. 
#  $(Process) will be a integer number for each job, starting with "0"
#  and increasing for the relevant number of jobs.
executable = hello-world.sh
arguments = $(Process)
		
# Specify the name of the log, standard error, and standard output (or "screen output") files. Wherever you see $(Cluster), HTCondor will insert the 
#  queue number assigned to this set of jobs at the time of submission.
	
log = hello-world_$(Cluster)_$(Process).log
error = hello-world_$(Cluster)_$(Process).err
output = hello-world_$(Cluster)_$(Process).out
	
 # This lines *would* be used if there were any other files
 # needed for the executable to use.
 # transfer_input_files = file1,/absolute/pathto/file2,etc
	
 # Tell HTCondor requirements (e.g., operating system) your job needs, 
 # what amount of compute resources each job will need on the computer where it runs.
request_cpus = 1
request_memory = 1GB
request_disk = 5GB
	
 # Tell HTCondor to run 3 instances of our job:
queue 3