# test_kmgpt.sub
# Configured for Docker universe to run a Docker container job in HTCondor

# Docker universe specification
universe = docker

# Specify the Docker image to use
docker_image = docker://lexu27/kmgpt_filter:v0.6
docker_pull_policy = missing

# The executable is a script or command that resides in the current directory
executable = run.sh
# Define the full command with argument substitution HERE in run.sub
arguments = python relevance.py --km_output $(Item) --config config.json

# Specify file transfer behavior and the files to be transferred
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = .

# Output, error, and log file settings
output = run_$(Cluster)_$(Process).out
error = run_$(Cluster)_$(Process).err
log = run_$(Cluster).log

# Request GPU resources
request_gpus = 1
requirements = (CUDACapability >= 8.0)
+WantGPULab = true
+GPUJobLength = "short"

# Resource requests
request_cpus = 1
request_memory = 24GB
request_disk = 50GB

stream_error = true
stream_output = true
